monolog:
  channels: ['four_media_integrity']
  handlers:
    fourMediaIntegrityHandler:
      type: rotating_file
      path: "%kernel.logs_dir%/four_media_integrity_%kernel.environment%.log"
      level: info
      channels: ["four_media_integrity"]
